server:
  port: 8082

spring:
  application:
    name: booking-provider-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5431/provider_service_db
  flyway:
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  config:
    import: ${configserver.import}
  cloud:
    config:
      import-check.enabled: false
      fail-fast: false

      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8098/eureka/
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true

configserver:
  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8089}